### ISSUE TITLE
Issue with dependency using gradle

### ISSUE THREAD

**Issue by VsevTrof** [minyushov/simple-numeric-keyboard#1]
I have a project that uses your keyboard. When Gradle tries to sync project getting dependency for your keyboard, I get error:
`Could not GET 'https://dl.bintray.com/minyushov/android/com/minyushov/android/numeric-keyboard/1.1.1/numeric-keyboard-1.1.1.pom'. Received status code 403 from server: Forbidden`
My dependency:
`implementation "com.minyushov.android:numeric-keyboard:1.1.1"`
Gradle also can't sync project with depency for your cameraview (it's a bit old project):
`implementation "com.minyushov.android:cameraview:2.1.0"` (if I use new dependency with **otaliastudios**, error disappears)
But at the same time my teammates (two more people) working on this project for a longer period of time doesn't have those errors, even if they load the same version of project from git. If you know what's wrong could you please explain how to fix it? And also could you explain please why I am the only one who gets such an error (I got it on office PC, on my laptop with Windows 10, even on Ubuntu 20.04 (for the first time I thought that's all about OS)) 
![photo_2021-06-01_23-24-30](https://user-images.githubusercontent.com/85196107/120385813-8dd00980-c330-11eb-9ae3-55b30c6ba8d5.jpg)

**Comment by minyushov** [comment]
This library (as well as cameraview) was hosted on private bintray repo which is not available anymore: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.

I've published a new version of the library to Maven Central. Please note that groupId is changed to `io.github.minyushov`, so your dependency should look like `implementation "io.github.minyushov:numeric-keyboard:1.2.0"`. Also if you don't have `mavenCentral()` in your repositories please add it.

As for `com.minyushov.android:cameraview`, you can safely replace it with the original library from **otaliastudios**.

Your teammates don't see these issues most likely because Gradle cached these libraries. If they try to clean Gradle cache they probably face the same issues as you.
